### PR TITLE
mocha recipe

### PR DESCRIPTION
**Pull request by DanielGluskin**
- Install mocha, chai & chai-subset
- basic test with mocha & chai
- mocha npm script
- 
should we add **npm run test:mocha** to the CI?

### CODE REVIEW

**Comment by goldbergyoni** [comment]
@DanielGluskin This is an important PR, once we have rich examples for so many things like Nest, MySQL, etc - This will make it a trustable source for many more people 👑

Basic questions before I delve into the small details:

1. Why isn't this a recipe? We should keep the main example as thin as possible
2. What starts the DB? The main Mocha difference is the global hook. It has some new hooks for this
3. Yes, CI must test everything that can fail
4. Optional: Let's configure Mocha for parallel testing, ~2 workers might be the optimal setup (based on my benchmarks with Jest)

@mikicho Thoughts before Daniel finalize this?

**Comment by DanielGluskin** [comment]
> @DanielGluskin This is an important PR, once we have rich examples for so many things like Nest, MySQL, etc - This will make it a trustable source for many more people 👑
> 
> Basic questions before I delve into the small details:
> 
> 1. Why isn't this a recipe? We should keep the main example as thin as possible
> 2. What starts the DB? The main Mocha difference is the global hook. It has some new hooks for this
> 3. Yes, CI must test everything that can fail
> 4. Optional: Let's configure Mocha for parallel testing, ~2 workers might be the optimal setup (based on my benchmarks with Jest)
> 
> @mikicho Thoughts before Daniel finalize this?

1. agreed. Does it mean that we should take the basic-exapmle for jest from there as well?
2. added.
3. not sure how to set it up.
4. sure, if everything is okey now.

**Comment by goldbergyoni** [comment]
> > @DanielGluskin This is an important PR, once we have rich examples for so many things like Nest, MySQL, etc - This will make it a trustable source for many more people 👑
> > Basic questions before I delve into the small details:
> > 
> > 1. Why isn't this a recipe? We should keep the main example as thin as possible
> > 2. What starts the DB? The main Mocha difference is the global hook. It has some new hooks for this
> > 3. Yes, CI must test everything that can fail
> > 4. Optional: Let's configure Mocha for parallel testing, ~2 workers might be the optimal setup (based on my benchmarks with Jest)
> > 
> > @mikicho Thoughts before Daniel finalize this?
> 
> 1. agreed. Does it mean that we should take the basic-exapmle for jest from there as well?
> 2. added.
> 3. not sure how to set it up.
> 4. sure, if everything is okey now.

1. No, the basic application must contain something. Our default is Jest/Expess. Anything else is a recipe
2. You sure this is the way to add global setup in a multi-process mode? They had some changes recently
https://twitter.com/goldbergyoni/status/1350543142664232963
3. Like Michael called the nestjs tests?
4. Not sure about the global setup, I would read a bit

**Review by mikicho — APPROVED** [review]

**Comment by goldbergyoni** [comment]
@DanielGluskin Need to merge with master

**Pull request merged**
